/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 dancingLeonard.gltf
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function DancingLeonard(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/dancingLeonard.gltf')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions.dance.play();
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorig9Hips} />
          <skinnedMesh name="Ch31_Body" geometry={nodes.Ch31_Body.geometry} material={materials['Ch31_body.001']} skeleton={nodes.Ch31_Body.skeleton} />
          <skinnedMesh name="Ch31_Collar" geometry={nodes.Ch31_Collar.geometry} material={materials['Ch31_body.001']} skeleton={nodes.Ch31_Collar.skeleton} />
          <skinnedMesh name="Ch31_Eyelashes" geometry={nodes.Ch31_Eyelashes.geometry} material={materials['Ch31_hair.001']} skeleton={nodes.Ch31_Eyelashes.skeleton} />
          <skinnedMesh name="Ch31_Hair" geometry={nodes.Ch31_Hair.geometry} material={materials['Ch31_hair.001']} skeleton={nodes.Ch31_Hair.skeleton} />
          <skinnedMesh name="Ch31_Pants" geometry={nodes.Ch31_Pants.geometry} material={materials['Ch31_body.001']} skeleton={nodes.Ch31_Pants.skeleton} />
          <skinnedMesh name="Ch31_Shoes" geometry={nodes.Ch31_Shoes.geometry} material={materials['Ch31_body.001']} skeleton={nodes.Ch31_Shoes.skeleton} />
          <skinnedMesh name="Ch31_Sweater" geometry={nodes.Ch31_Sweater.geometry} material={materials['Ch31_body.001']} skeleton={nodes.Ch31_Sweater.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/dancingLeonard.gltf')
